# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '7393a628-2eb3-49be-9c09-6bfd4d506015'
  imageRepository: 'app1nginx'
  containerRegistry: 'azaksdevopsacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
  name: default

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: default
    steps:
    # - task: Docker@2
    #   displayName: Build and push an image to container registry
    #   inputs:
    #     command: buildAndPush
    #     repository: $(imageRepository)
    #     dockerfile: $(dockerfilePath)
    #     containerRegistry: $(dockerRegistryServiceConnection)
    #     tags: |
    #       $(tag)
        
    - script: |
        sudo systemctl start docker
        sudo service docker status
        sudo docker rmi -f $(sudo docker images -aq)
        sudo docker build --rm -f Dockerfile -t app1-nginx $(Build.SourcesDirectory)
        sudo docker image ls -a
        sudo docker tag app1-nginx $(containerRegistry)/$(imageRepository):$(tag)
        sudo docker image ls -a
        sudo docker login $(containerRegistry)
        


